### ISSUE TITLE
Hygienic `syntax-rules`

### ISSUE THREAD

**Issue by raviqqe** [raviqqe/stak#209]
# Todo

## Macro definitions

- [x] Map global values to denotations.
- [x] Map global macros to denotations.
- [x] Map local values to denotations.
- [x] Map local macros to denotations.
- [x] Map special forms to denotations.
  - Primitives: `begin`, `if`, `lambda`, `quote`, and `set!`
  - Macros: `quasiquote`, `unquote`, `define-syntax`, `let-syntax`, `letrec-syntax`, ...
- [x] Escape new bindings introduced by macros.
  - They are created only by `lambda`.
- [x] Check literals' denotations on matching.
- [x] Refactor `expand`.

## Macro use

- [x] Shadow global values by macros.
- [x] Shadow global macros by values.
- [x] Shadow local values by macros.
- [x] Shadow local macros by values.

## Bugs

- #278
